### 없는 사용자 검색
GET http://localhost:8000/api/bot/0

> {%
    client.test("없는 사용자 검색", function () {
        client.assert(response.status === 404, "Response status is not 404");
    });
%}

### 관리자 사용자 조회
GET http://localhost:8000/api/user

> {%
    client.test("관리자 사용자 조회", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### 관리자 사용자 등록
POST http://localhost:8000/api/user
Content-Type: application/json

{
  "name": "홍길동",
  "tel": "010-0000-0000",
  "department": "NCT",
  "duty": "DEV",
  "is_lunch": true,
  "is_dinner": true
}

> {%
    client.test("관리자 사용자 등록", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### 관리자 사용자 수정
PUT http://localhost:8000/api/user/1
Content-Type: application/json

{
  "name": "홍길순",
  "tel": "010-0000-0001",
  "department": "NCT",
  "duty": "DEV",
  "is_lunch": true,
  "is_dinner": false
}

> {%
    client.test("관리자 사용자 등록", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### 사용자 등록
PUT http://localhost:8000/api/bot/1
Content-Type: application/json

{
  "name": "홍길순",
  "tel": "010-0000-0001",
  "department": "NCT",
  "duty": "DEV"
}

> {%
    client.test("관리자 사용자 등록", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### QR 생성
GET http://localhost:8000/api/bot/1/qr

> {%
    client.test("없는 사용자 검색", function () {
        client.assert(response.status === 200, "Response status is not 404");
    });
%}


### QR 생성
GET http://localhost:8000/api/bot/1/qr

> {%
    client.test("없는 사용자 검색", function () {
        client.assert(response.status === 200, "Response status is not 404");
    });
%}