### 없는 사용자 검색
GET http://localhost:8000/api/bot/0

> {%
    client.test("없는 사용자 검색", function () {
        client.assert(response.status === 404, "Response status is not 404");
    });
%}

### 관리자 사용자 조회
GET http://localhost:8000/api/user

> {%
    client.test("관리자 사용자 조회", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### 관리자 사용자 등록
POST http://localhost:8000/api/user
Content-Type: application/json

{
  "name": "김규형",
  "tel": "010-3038-8121",
  "department": "NCT",
  "duty": "DEV",
  "is_lunch": true,
  "is_dinner": true
}

> {%
    client.test("관리자 사용자 등록", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### 관리자 사용자 수정
PUT http://localhost:8000/api/user/1
Content-Type: application/json

{
  "name": "홍길순",
  "tel": "010-0000-0001",
  "department": "NCT",
  "duty": "DEV",
  "is_lunch": true,
  "is_dinner": true
}

> {%
    client.test("관리자 사용자 등록", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### 사용자 등록
PUT http://localhost:8000/api/bot/145842735
Content-Type: application/json

{
  "name": "홍길순",
  "tel": "010-0000-0001",
  "department": "NCT",
  "duty": "DEV"
}

> {%
    client.test("관리자 사용자 등록", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### QR 생성
GET http://localhost:8000/api/bot/145842735/qr

> {%

    // 응답에서 "code" 값을 추출하고 변수로 저장
if (typeof response.body === 'string') {
    const jsonResponse = JSON.parse(response.body);
    client.global.set("qrCode", jsonResponse.code);
    client.test("QR 생성 성공", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(jsonResponse.code !== undefined, "QR 코드가 응답에 없습니다.");
    });
} else {
    client.global.set("qrCode", response.body.code);

    client.test("QR 생성 성공", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.code !== undefined, "QR 코드가 응답에 없습니다.");
    });
}
%}

### QR 인증
GET http://localhost:8000/api/qr/{{qrCode}}

> {%
    // 저장된 QR 코드로 인증 요청 테스트
    client.test("QR 인증 성공", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
